"""Fix updated_at in users table

Revision ID: ae2da823b549
Revises: d149a22a288d
Create Date: 2024-08-15 18:04:18.806183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae2da823b549'
down_revision: Union[str, None] = 'd149a22a288d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op: batch_op.alter_column('updated_at', server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op: batch_op.alter_column('updated_at', server_default=None)
    # ### end Alembic commands ###
